.TH "DB_datatools.py" 3 "Thu Jan 25 2018" "Data Tools Package" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DB_datatools.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBDataTools\&.DB_datatools\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBDataTools\&.DB_datatools\&.db_connect\fP (dbfile)"
.br
.ti -1c
.RI "def \fBDataTools\&.DB_datatools\&.db_findrelations\fP (cursor, search_terms)"
.br
.ti -1c
.RI "def \fBDataTools\&.DB_datatools\&.db_findtarget_bysynonym\fP ()"
.br
.ti -1c
.RI "def \fBDataTools\&.DB_datatools\&.db_finddrug_bysynonym\fP ()"
.br
.ti -1c
.RI "def \fBDataTools\&.DB_datatools\&.db_addsynonymbylist\fP ()"
.br
.ti -1c
.RI "def \fBDataTools\&.DB_datatools\&.db_findtargetsynonyms\fP (curs, target)"
.br
.ti -1c
.RI "def \fBDataTools\&.DB_datatools\&.closeconnections\fP (conn, curs)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Data Tools Package from the source code\&.
