.TH "language_datatools.py" 3 "Thu Jan 25 2018" "Data Tools Package" \" -*- nroff -*-
.ad l
.nh
.SH NAME
language_datatools.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDataTools\&.language_datatools\&.DictionaryTagger\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBDataTools\&.language_datatools\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBDataTools\&.language_datatools\&.split\fP (text)"
.br
.ti -1c
.RI "def \fBDataTools\&.language_datatools\&.pos_tag\fP (sentences)"
.br
.ti -1c
.RI "def \fBDataTools\&.language_datatools\&.network_score\fP (network, add_polarity=True, flag_changes=True)"
.br
.ti -1c
.RI "def \fBDataTools\&.language_datatools\&.sentence_score\fP (sentence_tokens, previous_token, acum_score)"
.br
.ti -1c
.RI "def \fBDataTools\&.language_datatools\&.sentiment_score\fP (review)"
.br
.ti -1c
.RI "def \fBDataTools\&.language_datatools\&.weighted_sentence_score\fP (sentence_tokens)"
.br
.ti -1c
.RI "def \fBDataTools\&.language_datatools\&.weighted_sentiment_score\fP (review, matrix_flag)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Data Tools Package from the source code\&.
