.TH "network_datatools.py" 3 "Thu Jan 25 2018" "Data Tools Package" \" -*- nroff -*-
.ad l
.nh
.SH NAME
network_datatools.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBDataTools\&.network_datatools\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBDataTools\&.network_datatools\&.findnetworknodes\fP (network)"
.br
.ti -1c
.RI "def \fBDataTools\&.network_datatools\&.findaliases\fP (entitylist)"
.br
.ti -1c
.RI "def \fBDataTools\&.network_datatools\&.perceptronify\fP (network, indegree_max=8)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Data Tools Package from the source code\&.
