.TH "ps_datatools.py" 3 "Thu Jan 25 2018" "Data Tools Package" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ps_datatools.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBDataTools\&.ps_datatools\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBDataTools\&.ps_datatools\&.ps_read_csv\fP (filename, ps_format=True)"
.br
.ti -1c
.RI "def \fBDataTools\&.ps_datatools\&.ps_read_entitylist\fP (filename)"
.br
.ti -1c
.RI "def \fBDataTools\&.ps_datatools\&.ps_has_duplicates\fP (network)"
.br
.ti -1c
.RI "def \fBDataTools\&.ps_datatools\&.ps_return_duplicates\fP (network)"
.br
.ti -1c
.RI "def \fBDataTools\&.ps_datatools\&.ps_flag_duplicates\fP (network)"
.br
.ti -1c
.RI "def \fBDataTools\&.ps_datatools\&.ps_drop_duplicates\fP (network)"
.br
.ti -1c
.RI "def \fBDataTools\&.ps_datatools\&.ps_clean_ref\fP (network)"
.br
.ti -1c
.RI "def \fBDataTools\&.ps_datatools\&.ps_clean_sentence_tags\fP (s)"
.br
.ti -1c
.RI "def \fBDataTools\&.ps_datatools\&.ps_clear_end\fP (s)"
.br
.ti -1c
.RI "def \fBDataTools\&.ps_datatools\&.ps_replace_syntax\fP (s)"
.br
.ti -1c
.RI "def \fBDataTools\&.ps_datatools\&.ps_perceptronify\fP (in_network, max_indegree=8)"
.br
.ti -1c
.RI "def \fBDataTools\&.ps_datatools\&.ps_write_csv\fP (network, csv_name='network_please_rename\&.csv', exclude_unknown=False)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Data Tools Package from the source code\&.
